name: 👾 Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guilyx/pacman-contrib-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: output
